name: hive_box_manager_example
description: "Example project for hive_box_manager."
publish_to: 'none'
version: 0.0.1




environment:
  flutter: ">=3.38.0 <4.0.0"
  sdk: '>=3.10.0 <4.0.0'




dependencies:
  flutter:
    sdk: flutter
  fpdart: ^1.2.0
  hive_box_manager:
    path: ..
  hive_ce: ^2.19.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true