name: hive_box_manager
description: "FP-style abstraction layers for Hive boxes."
version: 0.0.1
repository: https://github.com/LahaLuhem/hive_box_manager






environment:
  sdk: '>=3.9.0 <4.0.0'






dependencies:
  collection: ^1.19.1
  fpdart: ^1.2.0
  hive_ce: ^2.15.1
  meta: ^1.16.0






dev_dependencies:
  mockito: ^5.5.1
  dart_bloom_filter: ^1.0.0
  shouldly: ^0.5.0+1
  test: ^1.26.3






cider:
  link_template:
    tag: https://github.com/LahaLuhem/hive_box_manager/releases/%version%
    diff: https://github.com/LahaLuhem/hive_box_manager/compare/%from%...%to%
